server:
  port: 8888

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  #配置数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db3?useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.java.pojo


#配置日志的输出
logging:
  level:
    org:
      #日志信息的打印
      springframework: DEBUG,error
    com:
      java:
        mapper: DEBUG

mzc:
  #为文件在磁盘中的真实路径
  imagesPath: file:G:\SpringBootTest\


#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

